### ISSUE TITLE
Demo for how to Save Card with PaymentIntents

### ISSUE THREAD

**Issue by vinnyvimto** [stripe/stripe-payments-demo#43] opened 2019-02-04 18:06 UTC
I can't seem to work out a way to save a card when making payment using the new PaymentIntents.

The old way of making a token on the client-side and passing this to the backend meant I could use the token as a source to make a customer and the card would be saved.

With PaymentIntents however, if I try to create a customer from the source returned from the Stripe.js handleCardPayment API call it throws an error: "The source you provided cannot be attached to the customer. It must be chargeable or pending.".

This has left me at an impasse. The only documentation I could find that covers [saving a source](https://stripe.com/docs/payments/payment-intents/usage#saving-sources) with PaymentIntents assumes you already have a customer and source.

Edit: Creating a customer when you create a PaymentIntent is the only way I can see to have cards saveable with the new PaymentIntents flow. Although minor it's a little annoying because a customer is made whenever a user hits the checkout rather than when they've made at least one payment.

**Comment by thorsten-stripe** [comment] 2019-02-07 10:19
@vinnyvimto thanks for raising this, we're still actively working on the docs.

When using `handleCardPayment`[0] it does a couple of things under the hood:

1. It creates a card source (tokenisation of card details)
2. It confirms the PaymentIntent with the source at which point the radar and SCA rules[1] are evaluated
3. Based on the outcome of the rules:
    1. do Strong Customer Authentication with 3D Secure if required & create the charge
    2. if no authentication is required create the charge

For your scenario, do you always want to create a customer object if there was a successful payment, or do you have a checkbox in your checkout form that decides whether a customer object is created or not?

[0] https://stripe.com/docs/stripe-js/reference#stripe-handle-card-payment
[1] https://stripe.com/guides/strong-customer-authentication

**Comment by vinnyvimto** [comment] 2019-02-10 16:13
@thorsten-stripe thanks for coming back to me.

For this scenario, there is a checkbox for saving a card that like you say used to decide whether a customer is created after submitting a form to the backend.

For the most seamless user experience with PaymentIntents, in the end, I just decided it was easier to make a call to my backend before calling `handleCardPayment`. This 'pre-call' does a number of things such as create a "pending" order on our end, update the PaymentIntent with shipping information, attach other metadata and create a customer if required to save a card.

If a customer leaves that page between this call and handleCardPayment they're then given an option to try and pay again. Moving an order from pending to completed happens via webhook and then updates the frontend via WebSocket.

Because this ended up being the route I took, it actually didn't matter too much what got sent through with the `handleCardPayment` call. At the time of opening this issue, however, I was really looking for a way to add shipping details and other metadata without having to hit my backend first. Shipping data being something that can only be added with new card sources.

I'd be interested to know what other flows people have generally come up with.

**Comment by thorsten-stripe** [comment] 2019-02-11 09:36
@vinnyvimto that sounds like a great solution for your use-case, thanks for sharing! We're thinking about allowing the creation of a customer object from a successful PaymentIntent which would allow you to shift the customer creation request outside of the checkout path. Would this be of interest to you?

**Comment by dsampaolo** [comment] 2019-02-26 12:03
YES, it would be of great interest !

**Comment by SpaceyRezum** [comment] 2019-03-19 20:48
+1 it would be great to be able to create a customer object and attach the source used in the paymentIntent

**Comment by loctrice** [comment] 2019-04-01 11:29
I think migrating to intents when there's application code already written would be much easier this way. By easier I mean less code and workflow would need to be changed.

**Comment by fthuk** [comment] 2019-05-14 07:46
+1 👍 I'm in the same position that @vinnyvimto initially described when this thread was opened.

We're using Stripe for charity donations; on the donation page, we're taking both one-off and recurring gifts using Stripe Elements. When the user-facing donation form is submitted, the payment details are checked and, if successful, a client-side Stripe token is return to the donation form and then the whole form (token, donor details and gift details) is passed to the server. The server then creates a customer and, depending on if the gift is a one-off gift or recurring gift, either a charge is applied (for a one-off gift) or a new subscription plan is created and added to the customer (for a recurring gift). If everything has happened correctly, the user is then sent to a 'Thank you' page and sent a receipt e-mail confirming their gift.

With PaymentIntents, I can't see that a corresponding workflow is possible without a serious code re-write. Any thoughts or advice would be very welcome.

**Comment by thorsten-stripe** [comment] 2019-05-14 10:48
@fthuk thanks for outlining your integration path. You can achieve this via the manual confirmation flow: https://stripe.com/docs/payments/payment-intents/quickstart#manual-confirmation-flow

Just note that you will need to go back to the client for performing authentication if required. Alternatively you can use the new Checkout, which also supports subscriptions now: https://stripe.com/docs/payments/checkout/server#create-subscriptions

**Comment by Fossil01** [comment] 2019-05-27 21:13
@thorsten-stripe So I need to create a payment method and not let Elements make an intent out of it straight away?

Then add the method to a customer, subscribe to a plan and then somehow create the intent with or without 3DS?

If so, why can't we just attach intents to a customer and then subscribe them?

**Comment by kernio** [comment] 2019-05-27 22:35
Same problem for me with `Checkout`. I can integrate it in a few minutes, but without proper handling of EU VAT, it useless :(
So right now I'm trying to integrate flow with a subscription manually.

**Comment by Fossil01** [comment] 2019-05-27 22:37
@kernio after hours of messing around I finally figured it out manually. Maybe I can save you some time.

Use Elements, to create a payment method (not intent), send that id to PHP and add it to a customer, also add it as their default payment method otherwise (weirdly) it wont work.

```"invoice_settings" => ["default_payment_method" => $paymentMethod]```

then create the subscription.

**Comment by thorsten-stripe** [comment] 2019-07-06 11:54
Quick follow-up that post-payment attachment of a payment method to a customer object is now available via the SCA off-session payment APIs: https://stripe.com/docs/payments/cards/saving-cards#saving-card-after-payment

**Comment by it-creed** [comment] 2019-07-10 11:16
> +1 it would be great to be able to create a customer object and attach the source used in the paymentIntent

Hi, is there an update on this one?

**Comment by thorsten-stripe** [comment] 2019-07-10 15:07
@it-creed yes, see the details in my last comment: https://github.com/stripe/stripe-payments-demo/issues/43#issuecomment-508920663
https://stripe.com/docs/payments/cards/saving-cards#save-payment-method

**Comment by PranayShah** [comment] 2019-07-11 07:51
It is crazy how the first (hence the only) added `PaymentMethod` is not the _default_ and you have to set it explicitly.

**Comment by thorsten-stripe** [comment] 2019-07-12 17:17
@PranayShah thanks for the feedback. While we understand that this adds complexity, we want our users to be more aware and explicit of what method they are charging. Payments regulation is evolving globally and requires merchants in certain regions to explicitly set up new cards via a non-payment authentication during which they have to present the terms of service. You can find more information on this here: https://stripe.com/en-US/guides/sca-payment-flows

**Comment by thorsten-stripe** [comment] 2019-08-07 07:57
We've published a video that specifically looks at customer management / card-on-file with regard to SCA which you might find helpful if you landed here: https://youtu.be/52oinv6BZ34

**Comment by thandaanda** [comment] 2019-08-27 12:31
I am saving PaymentMethod using: [https://stripe.com/docs/payments/cards/saving-cards#saving-card-after-payment](https://stripe.com/docs/payments/cards/saving-cards#saving-card-after-payment). However, when I query customer data, I don't see cards under `sources`. How can I show my users which cards are stored with our platform.

**Comment by thorsten-stripe** [comment] 2019-08-27 13:11
@thandaanda our recommendation is to store a list of your customer's payment methods (including the fingerprint, expiration date, billing address etc) in your own database. That way you don't have to ping the API for that data. Should you need to list the customer's payment methods, you can do so via the payment_methods endpoint: https://stripe.com/docs/api/payment_methods/list

**Comment by jahudka** [comment] 2019-08-30 19:43
Hi, I might have some issues with saving cards after payment using the PaymentIntents integration. For customers who don't yet have a saved payment method, the flow looks like this:
1) Customer hits a "Pay" button
2) UI calls `stripe.createPaymentMethod('card', element)`
3) UI calls backend, passing the ID of the payment method obtained in the previous step
4) Backend calls `stripe.paymentIntents.create()`, passing in the payment method ID, as well as `setup_future_usage: 'off_session', confirmation_method: 'manual', confirm: true`
5) If this fails because the card needs SCA, backend passes the client secret back to frontend, otherwise end
6) Frontend calls `stripe.handleCardAction(clientSecret)` and passes the ID of the returned payment intent to backend
7) Backend calls `const intent = stripe.paymentIntents.confirm(intentId)`
8) If payment method isn't saved yet, backend calls `stripe.customers.create({ payment_method: intent.payment_method })` and saves customer ID along with payment method ID, otherwise end

Payment using these saved credentials looks like this:
1) Backend calls `stripe.paymentIntents.create()`, passing in stored customer ID and payment method ID
2) Continue from 5) above

The issue is that when charging a saved card, SCA is always triggered - even for the `4000 0025 0000 3155` test card, which should only require SCA the first time around. I _think_ it might be because the first `paymentIntents.create()` backend call, where I pass in `setup_future_usage`, fails because it requires SCA and the payment intent is actually really created when I call `handleCardAction()` - but I can't pass the `setup_future_usage` to that, so the intent is created without that option.. or is it something else?

**Comment by thorsten-stripe** [comment] 2019-08-30 20:31
@jahudka the setup steps sound correct. For step 1) of "Payment using these saved credentials" are you passing the `off_session:true`[0] flag to the payment intent creation?

[0] https://stripe.com/docs/payments/cards/charging-saved-cards#create-payment-intent-off-session

**Comment by jahudka** [comment] 2019-08-30 21:15
@thorsten-stripe omg I wasn't, can't believe I missed that.. It works now! Although the `off_session` property of `Stripe.paymentIntents.IPaymentIntentCreationOptions` is missing in `@types/stripe` version `6.31.23` (which is the latest), so I had to convince TypeScript a little, but that's no biggie.. Thanks a lot!

**Comment by jahudka** [comment] 2019-08-30 22:34
Okay, now there's another issue - if I test with a card which _always_ requires SCA, during off-session attempts when the card has already been saved, things start to get wonky..

The initial `stripe.paymentIntents.create()` fails as expected (well, except for the fact that now instead of returning an `IPaymentIntent` object with the appropriate state, it throws a `StripeCardError` - but the client secret can be extracted from that too). But then I pass the client secret to the client side and call `stripe.handleCardAction()` and it fails; my console says that "[t]he PaymentIntent supplied is not in the requires_action state". Inspecting the intent object found on the `StripeCardError` exception thrown by `stripe.paymentIntents.create()` indeed shows that the intent is in the `requires_source` state, but the code of the error is `authentication_required` and the message says `Your card was declined. This transaction requires authentication.`. This is in accord with what the docs say: charging a saved card is supposed to fail with an `authentication_required` code and a `requires_payment_method` (resp. `requires_source`, in older API versions) state.

The docs say I should now "follow the on-session payment instructions from step 2". So I pass the client secret extracted from the error object back to my frontend, my frontend calls `stripe.handleCardAction()`.. and fails, telling me in the console that "[t]he PaymentIntent supplied is not in the requires_action state". This, too, is in accord with the docs - namely the fact that `handleCardAction()` only works with an intent in the `requires_action` state - but that effectively means that I have to switch to automatic confirmation now, doesn't it, because I'll have to call `stripe.handleCardPayment()` instead... what am I missing? SCA in off-session payments can't only support automatic confirmation, or does it?

**Comment by thorsten-stripe** [comment] 2019-08-31 07:08
@jahudka off_session is a confirm-time parameter and is not stored on the state of the PaymentIntent. You can extract the PaymentIntent ID from the error object and call confirm on it again with the saved payment method and omitting `off_session:true` which will default to false (on-session payment) which will then move the PaymentIntent into requires_action state. I'd recommend that you watch our Dev Chat on this topic, especially starting from 26:55[0] where we talk about the recovery flows.

[0] https://youtu.be/52oinv6BZ34?t=1616

**Comment by enzoferey** [comment] 2019-10-12 19:23
Hi everybody !

I have been in the comfortable situation of implementing a checkout flow from scratch today. I wanted to achieve something similar to what @jahudka wanted to migrate: users can either do a one-off payment or go for a subscription.

I ended up with this flow, which looks pretty more lightweight than manual `PaymentIntent` handling:

1. Client requests a `PaymentIntent` to the server as soon as we know the kind of payment we want to go for. For that, I'm sending a payload like this:

```js
{
  userData: {
    name: "Some name",
    email: "some@email.com",
  },
  amount: 123123,
  currency: "eur",
  isSubscription: true,
}
```

The `userData` field contains information that I want to attach to the customer I may create later on if the payment succeeds. Note that if you need to charge existing customers you could add to this payload another key to send the `customerId` to use in the creation of the `PaymentIntent`.

2. Server generates the `PaymentIntent`. The `userData` is stored temporally in the `metadata` field and if `isSubscription === true` we need to set `setup_future_usage = "off_session"`. Also, it's required to send `payment_method_types = ["card"]`. Something like this:

```js
const payload = {
  metadata: {
    userData: JSON.stringify(userData),
  },
  amount,
  currency,
  payment_method_types: ['card'],
};

if (isSubscription) {
  payload.setup_future_usage = 'off_session';
}

stripe.paymentIntents.create(payload);
```

Then it sends the `client_secret` field of the created `PaymentIntent` to the client.

3. The client receives the `client_secret` (setting it in the state or any other medium depending on your technology of choice), captures the values of the inputs (billing address and card data mainly) and uses `stripe.handleCardPayment()` passing the `payment_method_data` when the user presses the "pay" button. In my case looks something like this:

```js
const { paymentIntent, error } = await stripe.handleCardPayment(
  clientSecret,
  {
    payment_method_data: {
      billing_details: {
        ... some details
      },
    },
  }
);
```

Note that `handleCardPayment` handles the authentication part of SCA for you, so you don't need to do anything else on the client except providing feedback to the user based on the `error` key returned.

4. Finally, in a async way, the server receives via a webhook the `payment_intent.succeeded` event and takes care of creating a `Customer` using the data saved in `metadata` and based on the `setup_future_usage` value of the `PaymentIntent` creates a subscription or not (which we could use another field in `metadata` to differentiate). Note that when creating the customer you need to check if it's a subscription or not in order to add to the payload the `payment_method`:

```js
const customer = await stripe.customers.create({
  payment_method: intent.payment_method, // only if subscription, otherwise it throws an error
});
```

For the webhooks handling of the events, it was really useful to use the [Stripe CLI](https://stripe.com/docs/stripe-cli) and [this](https://stripe.com/docs/payments/payment-intents/verifying-status#webhooks) code snippet. The `endpointSecret` secret is a value that I was actually no able to find anywhere on the dashboard, but the Stripe CLI displays it when executing `stripe listen` (it has the structure "whsec_....`).

Hope it helps people coming in this SCA storm under deadlines 😄

**Comment by lucasgsati** [comment] 2019-11-20 21:32
Hello all, im working with Stripe and cloning cards, everything works for the first step, but when i want to select an stored card im getting "The payment method you provided has already been attached to a customer"

This is what im doing:

```
$getPaymentMethod = \Stripe\PaymentMethod::retrieve(
                $paymentMethodId
                  );

            $payment_method = \Stripe\PaymentMethod::retrieve(
                $getPaymentMethod->id
              );
        
            $getPaymentMethod->attach([
                'customer' => $this->customer->getStripeId(),
            ]);
```

**Comment by thorsten-stripe** [comment] 2019-11-25 07:47
@lucasgsati please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.

Closing this out as we now have dedicated demos for this at https://github.com/stripe-samples?q=sav

**Closed by thorsten-stripe** 2019-11-25 07:47 UTC
